name: deephaven-caddy

services:
  deephaven-foo:
    image: ghcr.io/deephaven/server:0.34.1
    volumes:
      - ./deephaven.prop:/opt/deephaven/config/deephaven.prop:ro

  deephaven-bar:
    image: ghcr.io/deephaven/server:0.34.1
    volumes:
      - ./deephaven.prop:/opt/deephaven/config/deephaven.prop:ro

  reverse-proxy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
