version: '3'

name: deephaven-caddy

services:
  deephaven-foo:
    image: ghcr.io/deephaven/server:0.17.0

  deephaven-bar:
    image: ghcr.io/deephaven/server:0.17.0

  reverse-proxy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
