version: '3'

name: deephaven-caddy

services:
  deephaven-foo:
    build: deephaven/

  deephaven-bar:
    build: deephaven/

  reverse-proxy:
    build: caddy/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
